# Account
DEFAULT_ACC_NAME = "New account holder"
DEFAULT_ACC_MIN_BALANCE = 0.0
DEFAULT_FEE_MULTIPLIER = 1.0
DEFAULT_STARTING_ACC_ID = 10000
ACC_ID_INCREMENT_VALUE = 1

# Chequing Account
CHEQUING_OVERDRAFT_LIMIT = -500
CHEQUING_INTEREST_CHARGE = 0.03
CHEQUING_BOUNCE_PENALTY = 25.0

# Savings
GOOD_STANDING_INTEREST = 0.02
SAVINGS_BALANCE_MIN_LIMIT = 1000
LOW_BALANCE_FEE = 10

# Term Savings
DEFAULT_TERM = 60
INITIAL_AVAILABLE_FUNDS = 0

# Transaction Log
LOG_FILE_NAME_FORMAT = "ACC_{}_log.txt"

# Transaction Log Entry
LOG_ENTRY_FORMAT = "{}{: <7}{:-<20}{}\n"
LOG_TIME_FORMAT = "%H:%M:%S"
